<?php
/*
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User Software Agreement (EULA).
 * It is also available through the world-wide-web at this URL:
 * http://www.harapartners.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to eula@harapartners.com so we can send you a copy immediately.
 *
 */
 frameset
?>
<?php

$blogMessage = $this->getblogarticle();
?>
<div>
    <div class="big_blog_muen">
    	<div class="big_blog_muen_titles"><a href="">首页</a></div>
    	<div class="big_blog_muen_titles"><a href="">会员专区</a></div>
    	<div class="big_blog_muen_titles"><a href="">康士达区</a></div>
    	<div class="big_blog_muen_titles"><a href="">指尖风景</a></div>
    	<div class="big_blog_muen_titles"><a href="">微课堂区</a></div>
    	<div class="big_blog_muen_titles"><a href="">暴风新闻</a></div>
    </div>
    <div class="big_left_one"></div>
    <div class="big_left_div">
    dfegerg
    </div>
    <div class="big_right_div">
    dfegerg
    </div>
</div>